import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navigation";
import Footer from "@/components/Footer";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: '300',
});

export const metadata = {
  title: "Kickzout.co | Authentic Streetwear in a town",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
